# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    projectDir: '%kernel.project_dir%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Admin/Entity/'
            - '../src/RolePlay/Entity/'
            - '../src/Site/Entity/'
            - '../src/Kernel.php'


    App\Admin\Controller\:
        resource: '../src/Admin/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Site\Controller\:
        resource: '../src/Site/Controller/'
        tags: [ 'controller.service_arguments' ]


    App\RolePlay\Controller\:
        resource: '../src/RolePlay/Controller/'
        tags: [ 'controller.service_arguments' ]
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # maintenance mode
    maintenance_listener:
        class: App\Site\Event\MaintenanceListener
        arguments:
            - '@twig'
            - '@App\Admin\Repository\ConfigurationRepository'
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }